
CREATE TABLE PRODUCT
(
PRODUCT_ID INT NOT NULL,
PRODUCT_NAME VARCHAR(30) NOT NULL,
PRODUCT_CATEGORY CHAR(30) NOT NULL,
PRODUCT_PRICE INT NOT NULL,
PRIMARY KEY(PRODUCT_ID)
);

CREATE TABLE CUSTOMER
(
CONTACT_NUMBER INT NOT NULL,
NAME CHAR(30) NOT NULL,
ADDRESS VARCHAR(30) NOT NULL,
PRODUCT_ID INT NOT NULL,
PRIMARY KEY(CONTACT_NUMBER),
FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
);

CREATE TABLE BILLING
(
BILLING_ID INT NOT NULL,
BILLING_DATE VARCHAR(30) NOT NULL,
PRODUCT_QUANTITY INT NOT NULL,
CUSTOMER_NUMBER INT NOT NULL,
PRODUCT_ID INT NOT NULL,
FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID),
FOREIGN KEY (CUSTOMER_NUMBER) REFERENCES CUSTOMER(CONTACT_NUMBER)
);


CREATE TABLE SERVICING
(
CUSTOMER_NUMBER INT NOT NULL,
PRODUCT_ID INT NOT NULL,
RECEIVING_DATE VARCHAR(30) NOT NULL,
DELIVERY_DATE VARCHAR(30) NOT NULL,
PROBLEM VARCHAR(30) NOT NULL,
FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID),
FOREIGN KEY (CUSTOMER_NUMBER) REFERENCES CUSTOMER(CONTACT_NUMBER)
);



